# Generated by Django 5.2.5 on 2025-09-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp_bac_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('bank', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=11)),
                ('model', models.CharField(max_length=11)),
                ('part', models.CharField(max_length=11)),
                ('data_start', models.DateField()),
                ('data_end', models.DateField()),
                ('date_invoice', models.DateField()),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atms', to='pp_bac_app.flow')),
                ('operations', models.ManyToManyField(blank=True, related_name='atms', to='pp_bac_app.operation')),
            ],
        ),
    ]
